### PR TITLE
Continue with index_results if no nodes are contactable

### PR DESCRIPTION
**Pull request by tonvoon**
Hi,

Please can you consider this pull request to continue when there are no nodes contactable.

We have integrated your perl module but our Elasticsearch instance is a bit flaky. We used to get messages such as:

```
# PROCESSING RESULTS FROM TEST FILE: t-core/58resolved_services.t
[NoNodes] ** No nodes are available: [http://192.168.16.54:11200], called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /opt/opsview/perl/lib/perl5/App/Prove/Elasticsearch/Indexer.pm line 176
```

before the whole test stopped.

This change now catches this particular failure (NoNodes), prints a message to standard out, and then continues. I think this is better as the test suite will have continued to run, rather than just stopping abruptly.

In our testing, it now continues testing as we would like:

```
# PROCESSING RESULTS FROM TEST FILE: t-core/63promote_hostgroups.t
Failed to index due to no nodes online - continuing: [NoNodes] ** No nodes are available: [http://192.168.16.54:11200], called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /opt/opsview/perl/lib/perl5/App/Prove/Elasticsearch/Indexer.pm line 177.
# PROCESSING RESULTS FROM TEST FILE: t-core/70performance-parsing.t
```

A test case has been included as well.

Thanks,
Ton

### CODE REVIEW

**Comment by teodesian** [comment]
Thanks for using the software!  Would you like for me to additionally either:
* attempt a re-upload at the end of the job group
* dump a blob which can then be re-uploaded later via say a tool on a cron?

**Comment by tonvoon** [comment]
Either sounds good!

**Comment by teodesian** [comment]
Sounds good -- I like your changeset, so I'll merge it and work on getting some retry logic and so forth this weekend.

**Comment by teodesian** [comment]
Added retry in 5c48510e1b611ba7a152ea04388a0df0164135cd, tests tomorrow night, and hopefully a new release by wednesday.

**Pull request merged**
